pipeline {
    agent any

    environment {
        NODE_ENV = 'production'
    }

    stages {
        stage('📥 Checkout Code') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/subhash466/react_Project.git',
                        credentialsId: 'my_tocken'
                    ]]
                ])
            }
        }

        stage('📦 Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('⚙️ Build React App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('🚀 Deploy to Web Server') {
            steps {
                // Delete old files from web server directory
                sh 'rm -rf /var/www/html/*'

                // Copy new build to web server directory
                sh 'cp -r build/* /var/www/html/'
            }
        }
    }

    post {
        success {
            echo '✅ React client deployed successfully!'
        }
        failure {
            echo '❌ Build or Deploy failed. Check logs.'
        }
    }
}
